import { jsPDF } from "jspdf";
import { currency } from "./quoteCalculator";

function fmtDate(iso) {
  if (!iso) return "-";
  const dt = new Date(iso);
  if (Number.isNaN(dt.getTime())) return "-";
  return dt.toLocaleDateString();
}

function text(v) {
  return String(v ?? "-");
}

export function exportQuoteProposal(quote) {
  if (!quote) {
    throw new Error("Missing quote data for PDF export.");
  }

  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const left = 48;
  const right = pageWidth - 48;
  const maxWidth = right - left;
  const lineGap = 18;
  let y = 52;

  const ensureSpace = (needed = 24) => {
    if (y + needed <= pageHeight - 48) return;
    doc.addPage();
    y = 52;
  };

  const title = (label) => {
    ensureSpace(36);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(label, left, y);
    y += 12;
    doc.setDrawColor(193, 157, 92);
    doc.line(left, y, right, y);
    y += 16;
  };

  const row = (label, value) => {
    const safeValue = text(value);
    const wrapped = doc.splitTextToSize(safeValue, maxWidth - 170);
    ensureSpace(lineGap * Math.max(1, wrapped.length) + 4);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${label}:`, left, y);
    doc.setFont("helvetica", "normal");
    doc.text(wrapped, left + 120, y);
    y += lineGap * Math.max(1, wrapped.length);
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Tony Catering Proposal", left, y);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Quote #${text(quote.quoteNumber)}`, left, y + 18);
  doc.text(`Created: ${fmtDate(quote.createdAtISO)}`, right, y, { align: "right" });
  doc.text(`Valid Through: ${fmtDate(quote.expiresAtISO)}`, right, y + 18, { align: "right" });
  y += 40;

  title("Client and Event");
  row("Customer", quote.customer?.name);
  row("Email", quote.customer?.email);
  row("Event Date", quote.event?.date);
  row("Start Time", quote.event?.time);
  row("Venue", quote.event?.venue);
  row("Guests", quote.event?.guests);
  row("Service Style", quote.event?.style);

  title("Selections");
  row("Package", quote.selection?.packageName || quote.selection?.packageId);
  row("Add-ons", (quote.selection?.addons || []).join(", ") || "-");
  row("Rentals", (quote.selection?.rentals || []).join(", ") || "-");
  row("Travel (miles RT)", quote.selection?.milesRT);
  row("Payment Method", quote.selection?.payMethod);
  row("Deposit Link", quote.payment?.depositLink || "-");

  title("Pricing");
  row("Base", currency(quote.totals?.base || 0));
  row("Add-ons", currency(quote.totals?.addons || 0));
  row("Rentals", currency(quote.totals?.rentals || 0));
  row("Labor", currency(quote.totals?.labor || 0));
  row("Travel", currency(quote.totals?.travel || 0));
  row("Service Fee", currency(quote.totals?.serviceFee || 0));
  row("Tax", currency(quote.totals?.tax || 0));

  ensureSpace(56);
  doc.setDrawColor(193, 157, 92);
  doc.line(left, y, right, y);
  y += 16;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total: ${currency(quote.totals?.total || 0)}`, left, y);
  y += 18;
  doc.text(`Deposit Due: ${currency(quote.totals?.deposit || 0)}`, left, y);

  y += 30;
  ensureSpace(20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Generated by Tony Catering Quote Wizard.", left, y);

  const filename = `${text(quote.quoteNumber || "quote")}-proposal.pdf`.replace(/[^\w.-]/g, "_");
  doc.save(filename);
}
